config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks",
    :registrations => "registrations/registrations"}
  resources :users
  root "static_pages#show"
  get "/pages/:page" => "static_pages#show"
  resources :reviews
  resources :comments
  resources :likes
  resources :admins
  resources :reports, only: :create
  resources :notis

  scope "(:locale)", locale: /en|jp|vn/ do
    root to: "static_pages#show"
  end
end

app/models/aji.rb
class Aji < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/noti.rb
class Noti < ApplicationRecord
  belongs_to :user

  enum state: [:unread, :read]
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user, optional: true
  has_many :comment
  has_many :like
  has_one :aji

  before_save :average_point

  def average_point
    self.average_point = (self.quality + self.place + self.service + self.price)/4
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:facebook]
  mount_uploader :avatar, AvatarUploaderUploader
  has_many :review

  def self.new_with_session params, session
    super.tap do |user|
      if data = session["devise.facebook_data"] &&
        session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = 'milktea123456'
      user.name = auth.info.name
    end
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def show;end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  def default_url_options
    { locale: I18n.locale }
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address, :birthday, :avatar])
  end

  private
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def facebook
    generic_callback("facebook")
  end

  def generic_callback(provider)
    @identity = User.from_omniauth(request.env["omniauth.auth"])

    @user = @identity || current_user
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, kind: provider.capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    comment = Comment.new
    comment.update_attributes comment_params
  end

  def update
    comment = find_comment
    comment.update_attributes comment_params
  end

  def destroy
    comment = find_comment
    comment.destroy
  end

  private
  def comment_params
    params.require(:comment).permit :review_id, :user_id, :content
  end

  def find_comment
    Comment.find_by_id(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    unless find_like
      like = Like.new
      like.update_attributes like_params
    end
  end

  def destroy
    get_like.destroy
  end

  private
  def like_params
    params.require(:like).permit :review_id, :user_id
  end

  def find_like
    User.find_by_id(current_user.id).like.where(review_id: like_params[:review_id]).present?
  end

  def get_like
    Like.find_by(user_id: current_user.id, review_id: params[:id])
  end
end

app/controllers/notis_controller.rb
class NotisController < ApplicationController
  before_action :authenticate_user!

  def update
    Noti.where(user_id: params[:id]).each do |noti|
      noti.state = 1
      noti.save
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!

  def create
    report = Report.new
    report.update_attributes report_params
  end

  private
  def report_params
    params.require(:report).permit :user_id, :review_id, :reason
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_review, only: [:show, :destroy]

  def index
    @like = current_user.like
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new review_params
    if @review.save!
      flash[:success] = t "Success Created"
      redirect_to review_path(@review)
    else
      flash[:danger] = t "Something Wrong"
      redirect_to :back
    end
  end

  def edit

  end

  def update

  end

  def show
  end

  def destroy
    review = @cur_review.title
    user = @cur_review.user_id
    noti = Noti.new
    noti.update_attributes user_id: user, review_title: review
    @cur_review.delete
    redirect_to admin_path
  end

  private
    def review_params
      params.require(:review).permit :title, :store, :price_from, :price_upto,
        :content, :image, :user_id, :quality, :place, :price, :service, :currency, :aji_id
    end

  def find_review
    @cur_review = Review.find_by id: params[:id]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
    @q = Review.ransack params[:q]
    # @q.sorts = %w(title created_at desc) if @q.sorts.empty?
    @reviews = @q.result.page(params[:page]).per 9

    if params[:menu]
      respond_to do |f|
        f.js{ render file: "static_pages/show.js.erb"}
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user =  User.find_by_id(params[:id]) 
  end

  def destroy
    user = User.find_by_id(params[:id])
    user.review.each do |rv|
      rv.delete
    end
    user.delete
    redirect_to admin_path(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/show.html.erb
<div class="container" style="margin-top: 70px;">
  <div class="row" style="font-size: 1.5em;">
    <div class="col-sm-2" style="height: 100%;">
      <p><i class="fa fa-user" aria-hidden="true"></i>
        <%= current_user.name %></p>
      <p id="admin-statistic-btn"> <%= t "admin.statistic" %> </p>
      <p id="admin-review-btn"> <%= t "admin.review" %> </p>
      <p id="admin-user-btn"> <%= t "admin.user" %> </p>
    </div>

    <div class="col-sm-10 container" style="background: rgba(200,241,207,0.82);">
      <div class="admin-statistic" style="padding: 10px;">
        <p style="font-size: 2em"><%= t "admin.statistic" %></p>
        <div class="col-sm-3" style="background: white; padding: 20px;
          margin: 10px;font-size: 2em">
          <span style="font-weight: bold; color: #0a163b"><%= Review.all.count %></span>
          <p style="font-size: .7em"><%= t "admin.review" %></p>
        </div>

        <div class="col-sm-3" style="background: white; padding: 20px;
          margin: 10px;font-size: 2em">
          <span style="font-weight: bold; color: #0a163b"><%= User.all.count %></span><span style="font-size: .5em!important"> (<%= User.where(provider: "facebook").count %> from FB)</span>
          <p style="font-size: .7em"><%= t "admin.user" %></p>
        </div>
      </div>

      <div class="admin-review hide">
        <span style="font-size: 2em"><%= t "admin.review" %></span>
        <% Review.all.each do |review| %>
          <div style="padding: 10px; border-bottom: 1px solid rgba(128,128,128,0.53)">
            <%= link_to review.title, review %>
            <%= t "admin.by" %> <span><%= review.user.name %></span>
            <span style="font-size: .6em"><%= review.created_at.strftime('%d/%m/%y') %></span>
            <div class="btn btn-primary"
              style="padding: 3px 10px; background: #ff5317; color: white; font-size: .7em">
              <%= link_to "DELETE", review, method: :delete, style: "color: white" %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="admin-user hide">
        <span style="font-size: 2em"><%= t "admin.user" %></span>
        <% User.all.each do |user| %>
          <div style="padding: 10px; border-bottom: 1px solid rgba(128,128,128,0.53)">
            <%= link_to user.name, user %>
            <% if user.isAdmin %>
              <div class="btn btn-primary"
                style="padding: 3px 10px; background: #00c365; color: white; font-size: .7em; color: white">
                <%= t("admin.admin") %>
              </div>
            <% else %>
              <div class="btn btn-primary"
                   style="padding: 3px 10px; background: #ff5317; color: white; font-size: .7em">
                <%= link_to t("admin.delete"), user, method: :delete, style: "color: white" %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('#admin-review-btn').on('click', function() {
      $('.admin-review').removeClass('hide');
      $('.admin-statistic').addClass('hide');
      $('.admin-user').addClass('hide');
    })

    $('#admin-statistic-btn').on('click', function() {
      $('.admin-review').addClass('hide');
      $('.admin-statistic').removeClass('hide');
      $('.admin-user').addClass('hide');
    })

    $('#admin-user-btn').on('click', function() {
      $('.admin-review').addClass('hide');
      $('.admin-statistic').addClass('hide');
      $('.admin-user').removeClass('hide');
    })
  })
</script>
<style>
  #admin-review-btn, #admin-statistic-btn, #admin-user-btn {
    background: rgba(30, 254, 210, 0.75);
    padding: 5px;
  }

  .unchoosen {
    background: rgba(58, 132, 254, 0.75) !important;
  }
</style>

app/views/layouts/_menu.html.erb
<div class="collapse navbar-collapse">
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li>
        <div class="nav-noti-btn" style="height: 30px; width: 30px; padding: 2px 11px;
            <% if Noti.where(user_id: current_user.id, state: 0).present? %>
              background: #e3b323;<% else %>background: #a8a3a8;<% end %>margin: 11px;">
            <span style="font-size: 1.3em; color: white">
              <%= Noti.where(user_id: current_user.id, state: 0).count %>
            </span>
        </div>
      </li>
      <li><%= link_to t("nav.write_review"), new_review_path %></li>

      <li class="dropdown1">
        <a class="dropdown-toggle">
          <%= t "nav.account" %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% if current_user.isAdmin %>
            <li><%= link_to t("nav.go_to_admin"), admin_path(current_user) %></li>
          <% end %>
          <li><%= link_to t("nav.my_profile"), user_path(current_user) %></li>
          <li><%= link_to t("nav.my_favorite"), reviews_path %></li>
          <li><%= link_to t("nav.setting"), edit_user_registration_path %></li>
          <li class="divider"></li>
          <li>
            <%= link_to t("nav.logout"), destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to t("nav.login"), new_user_session_path %></li>
      <li id="signup"><%= link_to t("nav.signup"), new_user_registration_path %></li>
    <% end %>
    <li class="dropdown">
      <a class="dropdown-toggle">
        <%= t "nav.language" %>
        <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "English", locale:"en" %></li>
        <li><%= link_to "Tiếng Việt", locale:"vn" %></li>
        <li><%= link_to "日本語", locale:"jp" %></li>
      </ul>
    </li>
  </ul>
  <% if current_user %>
    <div class="noti-field hide" style="background: #f5f3f7; position: absolute; padding: 15px;
      right: 15%; top: 80%; box-shadow: 4px 2px 4px 0 rgba(0,0,0,.12), 2px 2px 2px 0 rgba(0,0,0,.24);">
      <% Noti.where(user_id: current_user.id).each do |noti| %>
        <div style="padding: 5px 15px; border-bottom: 1px solid gray;">
          <span style="color: #113d85; font-weight: bold"><%= noti.review_title %></span> <%= t "nav.noti_message" %>
          <i class="fa fa-check-square-o" aria-hidden="true"
            title="<% if noti.state == "read" %><%= t "nav.noti_read" %><% else %><%= t "nav.noti_unread" %><% end %>"
            style="font-size: 1.5em; margin: 0 -10px 0 20px;
            <% if noti.state == "read" %>color: green;<% else %>color: gray;<% end %>"></i>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    <% if current_user %>
      $('.nav-noti-btn').on('click', function() {
        $('.noti-field').toggleClass('hide');
        var url = '/notis/' + <%= current_user.id %>
        $.ajax({
          beforeSend: function(xhr){
            xhr.setRequestHeader('X-CSRF-Token',
              $('meta[name="csrf-token"]').attr('content'));
          },
          type:'PUT',
          url: url,
        })
      });
    <% end %>
    $('.dropdown-toggle').on('mouseenter', function() {
      var a = $(this).next();
      $('.dropdown-menu').css('display','none');
      a.css('display', 'block');
      $(a).on('mouseleave', function() {
        $(a).css('display', 'none');
      })
    })
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Milkteaholic</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <!--<script src="http://mynameismatthieu.com/WOW/dist/wow.min.js"></script>-->
  <link href="//fonts.googleapis.com/css?family=Allan" rel="stylesheet">
  <link href="//fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
  <link href="//fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">
  <link href="//fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
  <link href="//fonts.googleapis.com/css?family=Chelsea+Market" rel="stylesheet">
  <link href="http://fonts.googleapis.com/icon?family=Oswald:300,400,700,900" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <%= javascript_include_tag "application", "data-turbolinks-track": "true" %>
</head>
<div class="navbar navbar-default navbar-static-top navbar-fixed-top" role="navigation" id="navbar">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon icon-bar"></span>
        <span class="icon icon-bar"></span>
        <span class="icon icon-bar"></span>
      </button>
      <%= link_to "Milkteaholic", root_path, id: "brand", class: "navbar-brand nav-btn", method: :get %>

    </div>
    <div class="collapse navbar-collapse">
      <%= render "layouts/menu" %>
    </div>
  </div>
</div>
<body>
<section class="view-port">
  <% if notice %>
    <div class="notice"><%= notice %></div>
  <% end %>
  <%= yield %>
</section>
</body>
</html>

app/views/reviews/_comment.html.erb
<div class="comment-field hide" style="background: #ffffff;
  padding: 10px;font-style: italic; font-size: 1em;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)">
  <div class="cur_comment">
    <% @cur_review.comment.each do |comment| %>
      <div class="comment-row" style="border: 1px solid rgba(168,168,168,0.65);margin: 5px 0;
        padding: 5px 10px;">
        <p class="comment-header"><%= link_to comment.user.name, comment.user %>
          <span style="color: gray; font-size: .7em;"><%= comment.created_at %></span>
          <% if comment.user == current_user %>
            <i class="fa fa-pencil-square-o absolute edit-comment" aria-hidden="true"
              style="right: 3%;font-size: 1.6em;"
              data-id="<%= comment.id %>"></i>
            <i class="fa fa-trash absolute delete-comment" aria-hidden="true"
              style="right: 0; font-size: 1.45em;color: #c0262e" data-id="<%= comment.id %>"></i>
          <% end %>
        </p>
        <p><%= comment.content %></p>
      </div>
    <% end %>
  </div>

  <div class="new-comment">
    <input type="textarea" style="width: 90%;
      height: 50px;" id="cmt-content-field">
    <div class="btn btn-comment"><%= t "review.comment" %></div>
    <div class="btn btn-edit hide"><%= t "review.comment_edit" %></div>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="container">
  <h1><%= t "review.fav" %></h1>
  <% @like.each do |like| %>
    <% review = Review.find_by_id like.review_id %>
    <% if review %>
      <% if review.image.url != nil %>
        <div class="col-sm-3 main-content-item1" style="background-image: url('<%= image_path(review.image.url) %>');
          background-size: cover; background-position: center; background-repeat: no-repeat;">
          <div class="item-content" style="font-size: 2em;">
            <%= link_to review.title.truncate(20), review, class: "review-title",
                        title: "#{review.title}" %><br>
            <div class="row" style="margin: 0">
              <div class="review-price-from col-sm-6">
                <%= t "home.review.from" %> <%= review.price_from %>
              </div>

              <div class="review-price-to col-sm-6">
                <%= t "home.review.to" %> <%= review.price_upto %>
              </div>
            </div>
          </div>

          <span class="review-star" style="">
          <%= review.average_point.round(1) %>
        </span>
        </div>
      <% else %>
        <div class="col-sm-3 main-content-item1" style="background-image: url('http://img1.cookinglight.timeinc.net/sites/default/files/styles/4_3_horizontal_-_1200x900/public/image/2016/12/main/grapefruit-soda.jpg?itok=VOZWdiFr');
          background-size: cover; background-position: center; background-repeat: no-repeat;">
          <div class="item-content" style="font-size: 2em;">
            <%= link_to review.title.truncate(20), review, class: "review-title",
                        title: "#{review.title}" %><br>
            <div class="row" style="margin: 0">
              <div class="review-price-from col-sm-6">
                <%= t "home.review.from" %> <%= review.price_from %>
              </div>

              <div class="review-price-to col-sm-6">
                <%= t "home.review.to" %> <%= review.price_upto %>
              </div>
            </div>
          </div>

          <span class="review-star" style="">
          <%= review.average_point.round(1) %>
        </span>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="col-sm-3">
    <img src="" alt="" id="img_prev" style="width: 100%; margin-top: 30px;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);">
  </div>
  <div class="form-new-review col-sm-9">
    <h2 class="text-center"><%= t "review.create" %></h2>
    <%= form_for :review, url: reviews_path, method: :post do |f| %>
      <div class = "field">
        <%= f.hidden_field :user_id, value: current_user.id %>
      </div>

      <div class="field">
        <%= f.label t("review.title") %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="field" style="margin-top: 10px;">
        <%= f.label t("review.flavour") %>
        <%= f.select :aji_id,
          Aji.all.collect { |type| [ "#{t("home.aji.#{type.label.downcase}")}", type.id ] },
          { include_blank: "#{t("review.select")}" },
          class:"ui dropdown js--select-event-type semantic-ui-form" %>
      </div>

      <div class="row">
        <div class="field col-sm-6">
          <%= f.label t("review.store") %>
          <%= f.text_field :store, autofocus: true, class: "form-control" %>
        </div>

        <div class="field col-sm-2">
          <%= f.label t("review.price_from") %>
          <%= f.number_field :price_from, class: "form-control", min: 0 %>
        </div>

        <div class="field col-sm-2">
          <%= f.label t("review.to") %>
          <%= f.number_field :price_upto, class: "form-control", min: 0 %>
        </div>

        <div class="field col-sm-2">
          <%= f.label t("review.currency") %>
          <%= f.text_field :currency, class: "form-control" %>
        </div>
      </div>

      <div style="padding: 10px 0; margin: 10px 0;">
        <div class="field" style="font-weight: bold; font-size: 1.2em"><%= t "home.rating" %></div>

        <div class="row" style="padding: 10px 0; background: rgba(210,247,213,0.64)">
          <div class="field col-sm-3">
            <%= f.label t("review.quality") %>
            <%= f.number_field :quality, class: "form-control", max: 10, min: 0 %>
          </div>
          <div class="field col-sm-3">
            <%= f.label t("review.place") %>
            <%= f.number_field :place, class: "form-control", max: 10, min: 0  %>
          </div>
          <div class="field col-sm-3">
            <%= f.label t("review.service") %>
            <%= f.number_field :service, class: "form-control", max: 10, min: 0  %>
          </div>
          <div class="field col-sm-3">
            <%= f.label t("review.price") %>
            <%= f.number_field :price, class: "form-control", max: 10, min: 0  %>
          </div>
        </div>
      </div>

      <div class="field">
        <%= f.label t("review.content") %><br />
        <%= f.text_area :content, class: "form-control form-control-content" %>
      </div>

      <div class = "field">
        <%= f.label t("review.image") %>
        <%= f.file_field :image, onchange: "readURL(this)" %>
      </div>
      <div class="actions">
        <%= f.submit t("review.save"), class: "btn btn-primary btn-form" %>
      </div>
    <% end %>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
</script>

app/views/reviews/show.html.erb
<div class="container" style="margin-top: 10vh">
  <div class="review-header">
    <div class="row" style="margin: 0 !important">
      <% if (@cur_review.image.url != nil) %>
        <div class="col-sm-5"
          style="background-image: url('<%= image_path(@cur_review.image.url) %>'); height: 300px;
          background-size: cover; background-position: center; background-repeat: no-repeat;">
        </div>
      <% else %>
        <div class="col-sm-5" style="background-image: url('http://img1.cookinglight.timeinc.net/sites/default/files/styles/4_3_horizontal_-_1200x900/public/image/2016/12/main/grapefruit-soda.jpg?itok=VOZWdiFr '); height: 300px;
          background-size: cover; background-position: center; background-repeat: no-repeat;">
        </div>
      <% end %>
      <%= render "right_header" %>
    </div>
  </div>

  <div class="review-field" style="background: #ffffff; min-height: 150px;
    padding: 10px;font-style: italic; font-size:1.2em;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)">
    <%= @cur_review.content %>
  </div>

  <%= render "comment" %>
</div>

<script type="text/javascript" charset="utf-8">
$('.main-rating').on('click', function(){
  $('.rating').toggleClass('hide');
});

$('.review-btn').on('click', function() {
  $(this).addClass("active");
  $('.comment-btn').removeClass('active');
  $('.review-field').removeClass('hide');
  $('.comment-field').addClass('hide');
});


$('.comment-btn').on('click', function() {
  $(this).addClass("active");
  $('.review-btn').removeClass('active');
  $('.review-field').addClass('hide');
  $('.comment-field').removeClass('hide');
});

<% if current_user  %>
  $(document).on('click', '.btn-comment', function() {
    var cmt_content = $('#cmt-content-field').val();
    $('#cmt-content-field').val('');
    $.ajax({
      beforeSend: function(xhr){
        xhr.setRequestHeader('X-CSRF-Token',
          $('meta[name="csrf-token"]').attr('content'));
      },
      type:'POST',
      url: '/comments',
      data: {
        comment: {
          content: cmt_content,
          review_id: <%= @cur_review.id %>,
          user_id: <%= current_user.id %>
        }
      }
    }).success(function(d){
      $('.cur_comment').load(document.URL + ' .cur_comment');
    });
  });

  $(document).on('click', '.delete-comment', function() {
    var url = '/comments/' + $(this).attr('data-id');
    $.ajax({
      beforeSend: function(xhr){
        xhr.setRequestHeader('X-CSRF-Token',
          $('meta[name="csrf-token"]').attr('content'));
      },
      type:'DELETE',
      url: url,
    }).success(function(d){
      $('.cur_comment').load(document.URL + ' .cur_comment');
    });
  });

  $(document).on('click', '.edit-comment', function() {
    var comment_id = $(this).attr('data-id');
    var cur_content = $(this).parent().next().text();
    $(this).parent().parent().hide();
    $('#cmt-content-field').val(cur_content);
    $('.btn-comment').hide();
    $('.btn-edit').removeClass('hide').on('click', function() {
      var new_content = $('#cmt-content-field').val();
      var edit_url = /comments/+comment_id;
      $.ajax({
        beforeSend: function(xhr){
          xhr.setRequestHeader('X-CSRF-Token',
            $('meta[name="csrf-token"]').attr('content'));
        },
        type:'PUT',
        url: edit_url,
        data: {
          comment: {
            content: new_content,
          }
        }
      }).success(function(d){
        $('.cur_comment').load(document.URL + ' .cur_comment');
        $('.btn-edit').addClass('hide');
        $('.btn-comment').show();
        $('#cmt-content-field').val('');
      });
    });
  });

  $(document).on('click', '#try-it', function() {
    $.ajax({
      beforeSend: function(xhr){
        xhr.setRequestHeader('X-CSRF-Token',
          $('meta[name="csrf-token"]').attr('content'));
      },
      type:'POST',
      url: '/likes',
      data: {
        like: {
          user_id: <%= current_user.id %>,
          review_id: <%= @cur_review.id %>,
        }
      }
    }).success(function(d){
      $('#like_field').load(document.URL + ' #like_field');
      $('.try-count').load(document.URL + ' .try-count-cont');
    });
  });

  $(document).on('click', '#un-try-it', function() {
    var url_delete = '/likes/' + <%= @cur_review.id %>;
    $.ajax({
      beforeSend: function(xhr){
        xhr.setRequestHeader('X-CSRF-Token',
          $('meta[name="csrf-token"]').attr('content'));
      },
      type:'DELETE',
      url: url_delete
    }).success(function(d){
      $('#like_field').load(document.URL + ' #like_field');
      $('.try-count').load(document.URL + ' .try-count-cont');
    });
  });
<% end %>
</script>

app/views/static_pages/show.js.erb
$('#review-zone').html('<%= j render "review", @reviews %>');
$('#pagination').html('<%= j paginate(@reviews,
  remote: true).to_s %>');